version: "3.9"

services:
  backend:
    container_name: coffee-be
    image: coffee-be-image
    build: ./backend
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    container_name: coffee-fe
    image: coffee-fe-image
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  mongodb:
    container_name: coffee-mongo
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
